-- PATIENT
create table if not exists patient(
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  created_at timestamp not null,
  updated_at timestamp not null,
  mrn varchar(64) not null,
  name varchar(128) not null,
  birth_date date,
  sex varchar(16),
  address varchar(256),
  phone varchar(32),
  emergency_contact varchar(256),
  consent_flags_json varchar(512)
);
create index if not exists idx_patient_tenant on patient(tenant_id);
create index if not exists idx_patient_mrn on patient(mrn);
create index if not exists idx_patient_name on patient(name);

-- ENCOUNTER
create table if not exists encounter(
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  created_at timestamp not null,
  updated_at timestamp not null,
  patient_id bigint not null,
  visit_date_time timestamp with time zone not null,
  department varchar(64),
  doctor_user_id varchar(64),
  reason varchar(256),
  vitals_json text,
  constraint fk_encounter_patient foreign key (patient_id) references patient(id)
);
create index if not exists idx_encounter_tenant on encounter(tenant_id);
create index if not exists idx_encounter_patient on encounter(patient_id);
create index if not exists idx_encounter_visit on encounter(visit_date_time);

-- NOTE
create table if not exists note(
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  created_at timestamp not null,
  updated_at timestamp not null,
  encounter_id bigint not null,
  author_user_id varchar(64),
  text text not null,
  created_at_z timestamp with time zone not null,
  constraint fk_note_encounter foreign key (encounter_id) references encounter(id)
);
create index if not exists idx_note_tenant on note(tenant_id);
create index if not exists idx_note_encounter on note(encounter_id);

-- AUDIT_LOG
create table if not exists audit_log(
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  created_at timestamp not null,
  updated_at timestamp not null,
  actor_user_id varchar(64) not null,
  action varchar(16) not null,
  resource_type varchar(64) not null,
  resource_id bigint not null,
  ip varchar(64),
  at timestamp not null
);
create index if not exists idx_audit_tenant on audit_log(tenant_id);
create index if not exists idx_audit_actor on audit_log(actor_user_id);
create index if not exists idx_audit_at on audit_log(at);
